### ISSUE TITLE
导入修复建议sql文件覆盖api_program后, django解析出错. 

### ISSUE THREAD

**Issue by 779789571** [Mustard404/Savior#10]
在dbeaver里面直接执行脚本, 导入了之后无法正确在django里面显示, 提示错误了..  感觉应该跟setting.py里面 DATABASES.OPTION'OPTIONS': {'charset': 'utf8mb4'} 有关系? 我不是非常懂django这部分, 麻烦大佬再解答下了. 
<img width="808" alt="image" src="https://user-images.githubusercontent.com/28771714/149110207-bf8f6b43-abb7-4f00-a4f7-ad4dba0a9ba7.png">
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/28771714/149110482-a42acf7e-2a4b-449a-8b06-e0de7b71c06a.png">

**Comment by Mustard404** [comment]
我没懂你要干什么，加我微信私聊吧。
![image](https://user-images.githubusercontent.com/14071947/149113352-69eb38dc-d5a3-4e2b-b7b2-0d5c0de69c94.png)

**Comment by 779789571** [comment]
mysql > show variables like '%char%';  
如果有latin, 修改为utf-8即可. 
<img width="662" alt="image" src="https://user-images.githubusercontent.com/28771714/149472226-1d64a733-6853-4e2b-a51b-6764e69a3674.png">
