### ISSUE TITLE
您好，请教您一个问题，我用您的方式修改了新的模板，选择完所有后，点击提交的时候报错，请问这是什么问题？

### ISSUE THREAD

**Issue by The-disappearing-world** [Mustard404/Savior#2]
您好，请教您一个问题，我用您的方式修改了新的模板，选择完所有后，点击提交的时候报错，请问这是什么问题？
![image](https://user-images.githubusercontent.com/35050364/144388366-6c6b6e05-5e87-4ac0-a6eb-0f04650ca4c4.png)

**Comment by Mustard404** [comment]
我猜是你的模板有问题，方便的话可以把模板发一下，我看下错误信息。

**Comment by The-disappearing-world** [comment]
您好，我的模板大致是这样的，只要在表格填入这些输入，就会报错，不在表格内填入就不会报错，请问是不支持这样的格式吗？
![image](https://user-images.githubusercontent.com/35050364/144394182-36b1869d-7927-4caf-b063-5c0e32a5d54f.png)

**Comment by Mustard404** [comment]
![image](https://user-images.githubusercontent.com/14071947/144425548-5767e18d-3906-46ac-81f1-5f72372fa5e1.png)
[demo.docx](https://github.com/Mustard404/Savior/files/7641949/demo.docx)

**Comment by Mustard404** [comment]
![image](https://user-images.githubusercontent.com/14071947/144425828-0354e830-0709-4613-8775-389b77b5317c.png)
我按照你的想法修改了相关的部分，漏洞部分你没加循环，而且有的是vuls.有的是item.，完全不符合语法。我把改好的样本放里面了，你到时候替换下
[demo.docx](https://github.com/Mustard404/Savior/files/7641963/demo.docx)

**Comment by The-disappearing-world** [comment]
太感谢大佬了，我去试试
