### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by 13226111270** [Mustard404/Savior#20]
当漏洞URL过长时会导致无法生成报告
![image](https://user-images.githubusercontent.com/59502740/199174472-fbd30bf5-ba04-44aa-8a23-90d96e2b7220.png)

**Comment by Mustard404** [comment]
可以通过修改/server/api/models.py中的vul_url参数的max_length字段用来满足项目要求

**Comment by 13226111270** [comment]
你好，我更改完了max_length的值但是还是显示了报错。更改为之后需要重新启动吗，还是啥问题呢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mustard404/Savior"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月11日(星期五) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mustard404/Savior] 小bug (Issue #20)





 
可以通过修改/server/api/models.py中的vul_url参数的max_length字段用来满足项目要求
