### ISSUE TITLE
踩坑提醒：word模板报错500

### ISSUE THREAD

**Issue by hkxueqi** [Mustard404/Savior#4]
![111111](https://user-images.githubusercontent.com/42443541/147340032-d6fb75e1-5d9e-4266-9dfe-b3ed3f2d9576.jpg)

r如图，我的报告写好语法，一直报错，我已经将内容删至最小化。

且语法是复制的dome.docx中测试可行的语法。

最终引发至于原因（在提issues 时写描述时突然虎躯一震发现了）
![image](https://user-images.githubusercontent.com/42443541/147340289-fc1495d6-33c0-4232-8f15-d8998e429615.png)

如上图，word文档格式一定要最新的.docx格式，.doc会引发错误

**Comment by hkxueqi** [comment]
一个下午就这么划没了

**Comment by Mustard404** [comment]
抱歉，我确实忽略了这个问题。在生成报告寻找模板时，确实以docx去进行拼接，才会导致此问题发生。感谢提交

[https://github.com/Mustard404/Savior/blob/master/server/api/auto_report_shell.py](url)
