### ISSUE TITLE
请问一下大佬如何增加一个字段

### ISSUE THREAD

**Issue by ht4266394** [Mustard404/Savior#5]
大佬看了你的项目简直开心的要飞起，因为真的是给我们解决了大问题（感动的哭了--）。现在有个问题请教，因为我们没几个专业写代码的，请问一下如果想在后台添加一个“测试账号”的填空，在报告中与之联动在哪个位置进行改动，这个联动的关键词是自己写的吗还是有标准，感谢大佬。

**Comment by Mustard404** [comment]
项目中没有预留改字段的位置，如果有需要只能自己改了。
大概修改内容如下：
前端：https://github.com/Mustard404/Savior/blob/master/app/src/pages/Report/index.jsx
后端：https://github.com/Mustard404/Savior/tree/master/server/api   的models.py，serializers.py 增加该字段参数。

**Comment by ht4266394** [comment]
> 项目中没有预留改字段的位置，如果有需要只能自己改了。 大概修改内容如下： 前端：https://github.com/Mustard404/Savior/blob/master/app/src/pages/Report/index.jsx 后端：https://github.com/Mustard404/Savior/tree/master/server/api 的models.py，serializers.py 增加该字段参数。

感谢大佬，还有一个问题，目录权限划分是怎么样的，我试了一下新增的用户都可以互相删除漏洞与报告
