### ISSUE TITLE
图片上传问题

### ISSUE THREAD

**Issue by wkend** [Mustard404/Savior#6]
添加漏洞，复现步骤那里如何添加图片呢

**Comment by Mustard404** [comment]
![image](https://user-images.githubusercontent.com/14071947/148688005-4b65f6df-6f17-4081-82b8-6185e1adc499.png)

**Comment by wkend** [comment]
整个图片插入多好，能实现就方便多了

**Comment by Mustard404** [comment]
学艺不精，这个富文本只会弄这种简单的方法。。。查了相关资料上传的话后续在转word会异常麻烦

**Comment by wkend** [comment]
很强了，膜！！！
