### ISSUE TITLE
源码部署时报错

### ISSUE THREAD

**Issue by ht4266394** [Mustard404/Savior#7]
大佬，我在源码部署时，执行yarn && yarn start:no-mock时报以下错误，是不是有模板没有安装上呢。yarn是v1.22.17，node版本是v16.13.1，大佬可否指点一二

warning "@ant-design/charts > @ant-design/flowchart > @antv/xflow > @antv/xflow-extension@1.0.21" has unmet peer dependency "reflect-metadata@^0.1.13".
warning "@ant-design/pro-table > react-sortable-hoc@2.0.0" has unmet peer dependency "prop-types@^15.5.7".
warning " > @ant-design/pro-table@2.62.1" has unmet peer dependency "rc-field-form@^1.x".
warning " > react-dev-inspector@1.7.1" has unmet peer dependency "@umijs/types@^3.2.20".
warning " > react-dev-inspector@1.7.1" has unmet peer dependency "webpack@>=4.44.1".
warning " > react-dev-inspector@1.7.1" has unmet peer dependency "webpack-chain@^6.5.1".
warning " > react-quill@1.3.5" has incorrect peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0".
warning "umi-serve > @babel/preset-typescript@7.3.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "umi-serve > @babel/register@7.4.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "umi-serve > @babel/preset-typescript > @babel/plugin-transform-typescript@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "umi-serve > @babel/preset-typescript > @babel/plugin-transform-typescript > @babel/helper-create-class-features-plugin@7.16.7" has unmet peer dependency "@babel/core@^7.0.0".
warning "umi-serve > @babel/preset-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@umijs/plugin-esbuild > esbuild-loader@2.9.2" has unmet peer dependency "webpack@^4.40.0 || ^5.0.0".
warning "@umijs/plugin-openapi > swagger-ui-react > react-inspector@2.3.1" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@umijs/plugin-openapi > swagger-ui-react > react-motion@0.5.2" has incorrect peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0".
warning "@umijs/plugin-openapi > swagger-ui-react > react-redux@4.4.10" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^15.4.0-0 || ^16.0.0-0".
warning "@umijs/preset-react > @umijs/plugin-dva > babel-plugin-dva-hmr@0.4.2" has unmet peer dependency "redbox-react@1.x".
warning "@umijs/preset-react > @umijs/plugin-dva > dva@2.6.0-beta.22" has incorrect peer dependency "react@^16.8.4".
warning "@umijs/preset-react > @umijs/plugin-dva > dva@2.6.0-beta.22" has incorrect peer dependency "react-dom@^16.8.4".
warning "@umijs/preset-react > @umijs/plugin-dva > dva-loading@3.0.22" has unmet peer dependency "dva-core@^1.1.0 | ^1.5.0-0 | ^1.6.0-0".
warning "@umijs/preset-react > @umijs/plugin-locale > react-intl@3.12.1" has incorrect peer dependency "react@^16.3.0".
warning "@umijs/preset-react > @umijs/plugin-dva > dva > connected-react-router@6.5.2" has incorrect peer dependency "react@^16.4.0".
warning "@umijs/preset-react > @umijs/plugin-dva > dva > connected-react-router@6.5.2" has unmet peer dependency "react-router@^4.3.1 || ^5.0.0".
warning " > jsdom-global@3.0.2" has unmet peer dependency "jsdom@>=10.0.0".

**Comment by Mustard404** [comment]
我这环境 yarn  1.22.10  node v14.15.3 开发没问题。warning报错直接忽略即可，只要不出现erroer就没事。

**Comment by Mustard404** [comment]
单独安装下 @ant-design/pro-list  再试下

**Comment by ht4266394** [comment]
> 单独安装下 @ant-design/pro-list 再试下

感谢大佬
