### ISSUE TITLE
源码部署后django管理后台static目录未能成功加载

### ISSUE THREAD

**Issue by 779789571** [Mustard404/Savior#8]
启动项目后,想进入django后台添加项目, 发现静态文件/static/目录未能成功加载, 烦请大佬解答下.. 谢啦
<img width="829" alt="image" src="https://user-images.githubusercontent.com/28771714/148909187-abce8784-7421-423f-95fb-bcae1ad53520.png">
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/28771714/148909308-1bb278f6-cb4d-4d04-a521-ad461c08d063.png">

**Comment by Mustard404** [comment]
我这测试正常，但是出现这个问题一般是https://github.com/Mustard404/Savior/blob/master/server/settings.py中的
```
STATIC_URL = '/static/'
STATIC_ROOT="static"
#STATIC_URL = '/server/api/static/'
# BASE_DIR 是项目的绝对地址
#STATIC_ROOT = os.path.join(BASE_DIR, 'collect_static')
```
出现问题了

或者把/Savior/static/  拷贝到 /Savior/static/server/api/目录好像也行

**Comment by 779789571** [comment]
重新启动莫名的就好了~
